spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # Put here your username
    username: (username)
    # Put here your password
    password: (password)
    url: jdbc:mysql://localhost:3306/mobilelele_db?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  jpa:
    #For MySQL 8 uncomment bellow (comment MySQL 5)
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5 (innodb dialect below)
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
